li=[18,23,21,22,18, 20]
li2=["jose", "miguel", "pablo"]
li2.insert(2, "juan")
li.append(24)
li.extend(li2)
li.pop()
li.pop(8)
li.remove("jose")
del(li[7])
print(li2.index("pablo"))
print(li2.index("pablo",0,4))
print(li)
print(li2)
li.reverse()
print(li)
def orde (valor):
    return len(valor)
li.sort()
print(li)
li.sort(reverse=True)
print(li)
li2.sort(key=orde)
print(li2)
print(li.count(18))
print(len(li))
print(len(li2))
print(sum(li))
print(max(li))
print(min(li))
